export enum MINUTES {
  ONE = 60000,
  TWO = MINUTES.ONE * 2,
  FIVE = MINUTES.ONE * 5,
  TEN = MINUTES.ONE * 10,
  TWENTY = MINUTES.ONE * 20,
}


export enum HOURS{
  ONE= MINUTES.ONE * 60,
  THREE= HOURS.ONE * 3,
  SIX= HOURS.ONE * 6,
  TWEVE= HOURS.ONE * 12,
  TWENTY_FOUR= HOURS.ONE * 24,
}